ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/include/     \
             -I$(srctree)/drivers/misc/mediatek/video/common/   \
             -I$(srctree)/drivers/misc/mediatek/video/common/rdma20/ \
             -I$(srctree)/drivers/misc/mediatek/video/common/wdma20/ \
             -I$(srctree)/drivers/misc/mediatek/video/common/layering_rule_base/v1.1/ \
             -I$(srctree)/drivers/misc/mediatek/video/mt6765/dispsys/ \
             -I$(srctree)/drivers/misc/mediatek/video/mt6765/videox/ \
             -I$(srctree)/drivers/misc/mediatek/sync/      \
             -I$(srctree)/drivers/misc/mediatek/mach/mt6765/include/mach/ \
             -I$(srctree)/drivers/misc/mediatek/base/power/mt6765/ \
             -I$(srctree)/drivers/misc/mediatek/base/power/include/ \
             -I$(srctree)/drivers/misc/mediatek/base/power/include/spm_v2/ \
             -I$(srctree)/drivers/misc/mediatek/smi/ \
             -I$(srctree)/drivers/misc/mediatek/dramc/mt6765/ \
             -I$(srctree)/drivers/misc/mediatek/gpu/ged/include/ \
             -I$(srctree)/drivers/iommu/  \
             -I$(srctree)/drivers/misc/mediatek/mmdvfs \
             -I$(srctree)/drivers/devfreq	\
             -I$(srctree)/include/linux/soc/mediatek

obj-m += fbflush.o
