obj-$(CONFIG_NICOCHRISTMANN_MTKMODS)            += mtkmods/
obj-$(CONFIG_NICOCHRISTMANN_USBWIFI)            += usbwifi/
obj-$(CONFIG_NICOCHRISTMANN_FBREFRESHTIMER)     += fbrefreshtimer/
obj-$(CONFIG_NICOCHRISTMANN_FBKMS)              += fbkms/
obj-$(CONFIG_NICOCHRISTMANN_FBKMS)              += fbkms_dev/
obj-y                                           += pstore_blk/
