obj-$(CONFIG_NICOCHRISTMANN_MTKMODS)            += kernelmodules/
obj-$(CONFIG_NICOCHRISTMANN_USBWIFI)            += usbwifi/
obj-m                                           += fbflush/
obj-m                                           += fbkms/
