obj-$(CONFIG_NICOCHRISTMANN_MTKMODS)            += mtkmods/
obj-$(CONFIG_NICOCHRISTMANN_USBWIFI)            += usbwifi/
obj-$(CONFIG_NICOCHRISTMANN_FBREFRESHTIMER)     += fbrefreshtimer/
obj-$(CONFIG_NICOCHRISTMANN_VKMS_COPY)          += vkms_copy/
obj-m                                           += fbkms/
