name: "build"
on:
  push:
      branches:
              - ice-s-oss

  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz > /dev/null && sudo xzcat clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz | sudo tar -x && sudo apt-get update > /dev/null && sudo apt-get install -y binutils gcc-arm-linux-gnueabi build-essential git flex bison libssl-dev bc libgmp-dev libmpc-dev jq wget curl unzip > /dev/null
        sudo ls clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin
        sleep 30
        wget github.com/Happynico7504/Xiaomi_Kernel_OpenSource/releases/download/build/buildcache.tar.gz > /dev/null && sudo zcat buildcache.tar.gz | sudo tar -x || true
        sudo ls buildcache
        sleep 30
    - run: "sudo PATH=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin:$PATH KBUILD_OUTPUT=buildcache COMPILERSETTINGS=\"-undefined,dynamic_lookup -fdata-sections -ffunction-sections -target=arm\" LINKERSETTNGS=\"-z nodefs\" ARCH=arm ARCH_MTK_PLATFORM=mt6761 CROSS_COMPILE=arm-linux-gnueabi- LLVM=1 KERNEL_DIR=$(pwd) CLANG_PREBUILT_BIN=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=/usr/bin CC=clang LD=llvm-link LLVM_LD=llvm-link AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip make -j$(nproc) || true"
    - run: "sudo tar -c buildcache | gzip -9 > buildcache.tar.gz"
    - run: "sleep 120"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "build"
        prerelease: true
        title: "Automatic build ${{ env.SHORT_SHA }}"
        files: |
          buildcache/arch/arm/boot/Image
          buildcache/arch/arm/boot/zImage
          buildcache/arch/arm/boot/Image.gz
          buildcache/.config
          clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz
          buildcache.tar.gz
