name: "build"
on:
  push:
      branches:
              - ice-s-oss

  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz > /dev/null && sudo xzcat clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz | sudo tar -x && sudo apt-get update > /dev/null && sudo apt-get install -y binutils gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu build-essential git flex bison libssl-dev bc libgmp-dev libmpc-dev jq wget curl unzip > /dev/null
        sudo ls clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin
        sleep 30
        nproc
        sleep 30
    - run: "sudo PATH=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin:$PATH KBUILD_OUTPUT=buildcache COMPILERSETTINGS=\"\" LINKERSETTNGS=\"-z nodefs\" ARCH=arm64 ARCH_MTK_PLATFORM=mt6761 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 KERNEL_DIR=$(pwd) CLANG_PREBUILT_BIN=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=/usr/bin CC=clang LD=ld.lld LLVM_LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip make -j$(nproc) && sudo cpp -nostdinc -I include -I buildcache/include -undef -x assembler-with-cpp arch/arm64/boot/dts/mediatek/mt6761.dts | sudo tee buildcache/redmi-a1.tmpdts && sudo ./buildcache/scripts/dtc/dtc -O dtb -o buildcache/redmi-a1.dtb buildcache/redmi-a1.tmpdts || true"
    - run: |
         sudo wget https://github.com/Happynico7504/MTK_kernel_modules/archive/refs/heads/ice-s-oss.zip
         sudo unzip ice-s-oss.zip
         sudo cp -r MTK_kernel_modules-ice-s-oss/* drivers/misc/mediatek
    - run: "sudo PATH=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin:$PATH KBUILD_OUTPUT=buildcache COMPILERSETTINGS=\"\" LINKERSETTNGS=\"-z nodefs\" ARCH=arm64 ARCH_MTK_PLATFORM=mt6761 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 KERNEL_DIR=$(pwd) CLANG_PREBUILT_BIN=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=/usr/bin CC=clang LD=ld.lld LLVM_LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip make modules -j$(nproc)"
    - run: "cp $(sudo find -iname *.ko) modules"
    - run: "sudo tar -c modules | gzip -9 > modules.tar.gz"
    - run: "sudo tar -c buildcache | gzip -9 > buildcache.tar.gz"
    - run: "sleep 120"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "autobuild"
        prerelease: true
        title: "Automatic build ${{ env.SHORT_SHA }}"
        files: |
          buildcache/arch/arm64/boot/Image
          buildcache/arch/arm64/boot/Image.gz
          buildcache/kheaders_data.tar.xz
          buildcache/System.map
          buildcache/.config
          clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz
          buildcache.tar.gz
          modules.tar.gz
