name: "build"
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo apt-get update && sudo apt-get install -y gcc-arm-linux-androideabi-4.9 binutils build-essential git flex bison libssl-dev bc libgmp-dev libmpc-dev jq
    - run: "make -j1"
      env:
        ARCH: "arm"
        CROSS_COMPILE: "arm-linux-androidkernel-"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development build ${{ env.SHORT_SHA }}"
        files: |
          arch/arm/boot/zImage
