name: "build"
on:
  push:
      branches:
              - ice-s-oss

  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        wget <gcc-link> && sudo dpkg install kernel-cc.deb && sudo apt-get update && sudo apt-get install -y binutils build-essential git flex bison libssl-dev bc libgmp-dev libmpc-dev jq wget curl
    - run: "make -j1"
      env:
        ARCH: "arm"
        CROSS_COMPILE: "arm-linux-gnueabi-"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development build ${{ env.SHORT_SHA }}"
        files: |
          arch/arm/boot/zImage
