name: "build"
on:

  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo apt-get update && sudo apt-get install -y binutils build-essential git flex bison libssl-dev bc libgmp-dev libmpc-dev jq wget curl
        wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12-dev.tar.gz
        gzip -d android12-dev.tar.gz
        tar -xf android12-dev.tar
        rm android12-dev*
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-dev.tar.gz
        gzip -d android12-dev.tar.gz
        tar -xf android12-dev.tar
        rm android12-dev*
        sudo cp -r bin lib libexec clang-r416183b1/* /
      
    - run: "make -j1"
      env:
        ARCH: "arm"
        CROSS_COMPILE: "arm-linux-androidkernel-"
        CC: "clang"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development build ${{ env.SHORT_SHA }}"
        files: |
          arch/arm/boot/zImage
