name: "Release Pipeline (selfhosted)"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "local-pc"
    steps:
    
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        wget https://github.com/Happynico7504/MTK_kernel_modules/archive/refs/heads/ice-s-oss.zip > /dev/null || true
        unzip ice-s-oss.zip || true
        cp -r MTK_kernel_modules-ice-s-oss/* drivers/misc/nicochristmann/kernelmodules || true
        git clone https://github.com/morrownr/88x2bu-20210702.git drivers/misc/nicochristmann/usbwifi
        xzcat /home/runner/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz | tar -x
        ls clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin
        sleep 15
        nproc
        sleep 15
    - run: "PATH=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin:$PATH KBUILD_OUTPUT=buildcache COMPILERSETTINGS=\"\" LINKERSETTNGS=\"-z nodefs\" ARCH=arm64 ARCH_MTK_PLATFORM=mt6761 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 KERNEL_DIR=$(pwd) CLANG_PREBUILT_BIN=$(pwd)/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10/bin LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=/usr/bin CC=clang LD=ld.lld LLVM_LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip make -j128 || true"
    - run: "cp $(find -iname *.ko) modules || true"
    - run: "tar -c modules | gzip -9 > modules.tar.gz"
    - run: "tar -c buildcache | gzip -9 > buildcache.tar.gz"
    - run: |
        sha512sum buildcache.tar.gz > buildcache.tar.gz.sha512 || true
        sha512sum modules.tar.gz > modules.tar.gz.sha512 || true
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "selfhosted-autobuild"
        prerelease: true
        title: "Automatic build ${{ env.SHORT_SHA }}"
        files: |
          buildcache/arch/arm64/boot/Image.gz
          buildcache/kernel/kheaders_data.tar.xz
          buildcache/System.map
          buildcache.tar.gz
          buildcache.tar.gz.sha512
          modules.tar.gz
          modules.tar.gz.sha512
